server:
  port: 8089

spring:
  application:
    name: ingestion-service
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

debezium:
  connector:
    name: micro-takeout-connector
    database:
      hostname: localhost
      port: 5432
      user: postgres
      password: postgres
      dbname: micro_takeout
    plugin:
      name: pgoutput

logging:
  level:
    com.microtakeout.ingestion: DEBUG

